- hosts: all
  become: yes
  ignore_errors: yes
  remote_user: ubuntu
  tasks:
   - name: install apache
     apt:
      name: apache2
      state: latest
     notify: restart apache2
   - name: copy html file
     copy:
      src: html
      dest: /home/ubuntu
  handlers:
   - name: restart apache2
     service:
      name: apache2
      state: restarted
      enabled: yes
